name: fajr
description: "Azan Al Fajr."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0+1
  shared_preferences: ^2.5.3
  country_picker: ^2.0.21
  path_provider: ^2.1.5
  audioplayers: ^6.0.0
  intl: ^0.20.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/country_coords.json
